version: '3'

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  database:
    driver: local
